server:
  port: 7000

spring:
  application:
    name: scp-api-manager
  # DataSource Config
  datasource:
    hikari:
      idle-timeout: 200000
      maximum-pool-size: 10
      minimum-idle: 30
      connection-timeout: 600000
      connection-test-query: SELECT 1
      pool-name: HikariPool
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&allowMultiQueries=true
    username: root
    password: 123456


# Logger Config
logging:
  level:
    com.demo.mp.mapper: debug #info

# Mybatis-plus Config
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lv.cloud.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${server.port}
    prefer-ip-address: true # 开启以Ip+端口多方式显示Eureka界面
  client:
    serviceUrl:
      defaultZone: http://peer1:9009/eureka/,http://peer2:9010/eureka/