server:
  port: 5555

spring:
  application:
    name: scp-zuul-service
  cloud:
    config:
      uri: http://localhost:8888/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:9009/eureka/,http://peer2:9010/eureka/
  instance:
    prefer-ip-address: true
    appname: scp-zuul-service

zuul:
  ignore-local-service: true
  ignored-services: scp-eureka
  prefix: /api
  routes:
    hello-service: /hs/**